# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  flash:
    cmds:
      - docker compose run --rm esphome upload battery.yaml --device /dev/ttyUSB0

  compile:
    cmds:
      - docker compose run --rm esphome compile battery.yaml
